### ISSUE TITLE
Metal Shaders support

### ISSUE THREAD

**Issue by yaroslavyaroslav** [swiftlang/sourcekit-lsp#1586]

**Comment by ahoppen** [comment]
Synced to Apple’s issue tracker as rdar://132478984

**Comment by yaroslavyaroslav** [comment]
Haven't tried it with `sourcekit-lsp` directly, but this config works well with `clangd`.

Put `.clangd` in the root folder of the project with the following content:

```yaml
If:
  PathMatch: .*\.metal?

CompileFlags:
  Add:
    - '--std'
    - 'c++17'
    - '-x'
    - 'c++'
    - '-I'
    - '/System/Library/Frameworks/Metal.framework/Headers'  # Metal framework headers
    - '-I'
    - '/System/Library/PrivateFrameworks/GPUCompiler.framework/Versions/32023/Libraries/lib/clang/32023.401/include/metal/'  # Path to metal_stdlib
```

After `clangd` server restarted completion works well with in `metal` files in Sublime Text.

@ahoppen I wonder if it's worth it to mention this configuration somewhere in the sourcekit-lsp docs to ease other folks of cracking that down?
